### PR TITLE
WIP: More advanced settings

### PR DESCRIPTION
**Pull request by donaldwasserman**
@ivanvanderbyl I'll just leave my commits here for the moment

From #80 

- [x] Implement route event handler so we can update intercom when changing route, as per Single Page app recommendation
- [x] Docs

### CODE REVIEW

**Comment by ivanvanderbyl** [comment]
This is looking really good @donaldwasserman

**Comment by ivanvanderbyl** [comment]
It looks like CI is failing because of an older Node version. If we bump that to `stable` or `>6` it should be okay.

**Comment by donaldwasserman** [comment]
I'm going to tackling the README over the weeekend. It seems like all the todos are accomplished.

**Comment by donaldwasserman** [comment]
I copied `ember-cli-babel`'s node config, just because I happened to be looking at it on a different project. 

@ivanvanderbyl  Let me know what else you'd like to get done before moving ahead. 

Are you planning on doing some sort of beta/rc release? What blockers remain?

**Comment by donaldwasserman** [comment]
@ivanvanderbyl I don't know enough about how fastboot works to resolve: `Cannot find module 'fastboot'`. 

Any thoughts? What else do we need to get done to get this to some sort of alpha-ish release?

**Comment by donaldwasserman** [comment]
@ivanvanderbyl So I've added additional tests/documentation. 

I'll be implementing this on my app today from my branch to test it out.

**Comment by ivanvanderbyl** [comment]
Hey @donaldwasserman sorry I didn't get back to you on this. If you feel like rebasing, I'll merge and release this today.

**Comment by donaldwasserman** [comment]
@ivanvanderbyl after looking at this, I think there's been so many changes, I'm just going to open up a new pr with some new functionality.

**Pull request closed without merging**
