### PR TITLE
Revert "User hash / secure mode support"

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
Reverts mike-north/ember-intercom-io#136 temporarily

### CODE REVIEW

**Comment by bgentry** [comment]
Did I break something?

**Comment by ivanvanderbyl** [comment]
Nah, I didn't see your earlier PRs and merged this too early, but it's okay because you included the first 2 in this one.

**Comment by ivanvanderbyl** [comment]
That revert didn't get merged.

**Comment by bgentry** [comment]
oh ok cool :) Can you also publish release when you get a chance? 🙏

**Comment by ivanvanderbyl** [comment]
I've prepared the release, but we'll need @mike-north to 🚢 to NPM.

**Comment by mike-north** [comment]
@ivanvanderbyl  published 0.3.0

**Pull request closed without merging**
