### PR TITLE
[WIP] (Feature) More advanced Intercom integration

### PR DESCRIPTION
**Pull request by ivanvanderbyl**
TODO:

- [x] Add method calls for all Intercom APIs
- [x] Add event handling for state tracking (open, close, unread count, etc.),
- [x] Expose unreadCount, isOpen, isBooted,
- [ ] Documentation
- [x] Implement `intercom-button` component which launches the Intercom messenger in the desired state,
- [ ] Implement route event handler so we can update intercom when changing route, as per [Single Page app recommendation](https://docs.intercom.com/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app),
- [x] Expose show and hide with promises,
- [ ] Add tests for all other API calls,
- [x] Convert intercom data keys to snake_case,
- [x] Convert dates to Unix timestamps,
- [x] auto update Intercom when user data changes,

Use-cases to document:

- [ ] Showing Intercom in Acquire mode when not signed in,
- [ ] Switching to signed in mode, and rebooting intercom when changing session,

### CODE REVIEW

**Comment by donaldwasserman** [comment]
Hey @ivanvanderbyl - I was going to submit a PR with the additional intercom methods then I saw your PR. 

Is there anything you want some help on to move this along?

**Comment by ivanvanderbyl** [comment]
@donaldwasserman if you can help with any of the remaining items at the top, that'd be a huge help

**Comment by donaldwasserman** [comment]
Sure - I'm actually headed to Ember conf this week, but try to get a lot of
that done in the next few weeks. I want some of the extra intercom methods
:)

**Comment by ivanvanderbyl** [comment]
@donaldwasserman see you at EmberConf :)

**Comment by donaldwasserman** [comment]
@ivanvanderbyl - what's going on with this?

**Comment by donaldwasserman** [comment]
@ivanvanderbyl Is there a way we can get this wrapped up (along with #94) to get some these more advanced API's done? I'd be happy to wrap up whatever else needs to get done between the two PRs.

**Comment by ivanvanderbyl** [comment]
@donaldwasserman I've got it on my list. If we can finish the documentation and maybe some basic tests it should be able to :shipit:

**Comment by donaldwasserman** [comment]
I don't really remember where I left off with some documentation. I can take a stab at some that this week. 

Would it be possible to merge some of the stuff you have plus what I have into a feature or development branch?

**Comment by ivanvanderbyl** [comment]
@donaldwasserman Yeah definitely, I think that'd make sense.

**Comment by donaldwasserman** [comment]
Hey @ivanvanderbyl Any updates on this? There's a handful of open issues that could be solved with the various efforts around this.

**Comment by mike-north** [comment]
Superceded by #143

**Pull request closed without merging**
